# Generated by Django 5.0.3 on 2024-03-13 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='DemandForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('nos', models.CharField(max_length=100)),
                ('consignee_name', models.CharField(max_length=100)),
                ('consignee_officer', models.CharField(max_length=100)),
                ('consignee_code', models.CharField(max_length=50)),
                ('demand_code', models.CharField(max_length=50)),
                ('allocation_number', models.CharField(max_length=50)),
                ('accounts_unit', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Accepted', 'Accepted')], default='Pending', max_length=50)),
                ('declained_reason', models.TextField(null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DemandRegister.product')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_name', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('complaint', models.TextField()),
                ('slnoItem', models.BigIntegerField()),
                ('dom', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DemandRegister.product')),
            ],
        ),
    ]
