# Generated by Django 5.0.3 on 2024-03-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('number', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('nos', models.CharField(max_length=100)),
                ('consignee_name', models.CharField(max_length=100)),
                ('consignee_officer', models.CharField(max_length=100)),
                ('consignee_code', models.CharField(max_length=50)),
                ('demand_code', models.CharField(max_length=50)),
                ('allocation_number', models.CharField(max_length=50)),
                ('accounts_unit', models.CharField(max_length=100)),
            ],
        ),
    ]
