# Generated by Django 5.0.3 on 2024-03-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemandRegister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandform',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
