# Generated by Django 5.0.3 on 2024-03-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemandRegister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plno',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
